steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/skin-type-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/skin-type-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'skin-type-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/skin-type-api'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/skin-type-api'